language: cpp

matrix:
  include:
    - compiler: gcc
      env: DO_COVERAGE=yes
    - compiler: clang
      env: DO_COVERAGE=no

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install build-essential libssl-dev libz-dev libsqlite3-dev libcurl4-gnutls-dev libdaemon-dev automake autoconf pkg-config libtool libcppunit-dev libnl-3-dev libnl-cli-3-dev libnl-genl-3-dev libnl-nf-3-dev libnl-route-3-dev libarchive-dev
  - sudo pip install cpp-coveralls

before_script:
  - cd ibrdtn

script:
  - ./autogen.sh
  - ./configure-dev --disable-netlink --enable-gcov
  - make
  - make check

after_success:
  - rm ibrdtn/ibrcommon; mv ibrcommon ibrdtn/ibrcommon
  - rm $(find -name '*.gcno' | grep -v '.libs')
  - if [ "${DO_COVERAGE}" == "yes" ]; then
      coveralls -r $(pwd)/ibrdtn --exclude ibrcommon/tests --exclude ibrdtn/tests --exclude daemon/tests --exclude tools --gcov-options '\-lp';
    fi

