/*
 * ContentStorageEntry.h
 *
 *  Created on: Jul 2, 2015
 *      Author: jeremy
 */

#ifndef IBRDTN_DAEMON_SRC_ROUTING_DISTANCE_CONTENTSTORAGEENTRY_H_
#define IBRDTN_DAEMON_SRC_ROUTING_DISTANCE_CONTENTSTORAGEENTRY_H_





#endif /* IBRDTN_DAEMON_SRC_ROUTING_DISTANCE_CONTENTSTORAGEENTRY_H_ */
