/*
 * PendingInterestTableEntry.h
 *
 *  Created on: Jul 3, 2015
 *      Author: jeremy
 */

#ifndef IBRDTN_DAEMON_SRC_ROUTING_DISTANCE_PENDINGINTERESTTABLEENTRY_H_
#define IBRDTN_DAEMON_SRC_ROUTING_DISTANCE_PENDINGINTERESTTABLEENTRY_H_





#endif /* IBRDTN_DAEMON_SRC_ROUTING_DISTANCE_PENDINGINTERESTTABLEENTRY_H_ */
